/* INSERTS DE CADA ROL*/
INSERT INTO ryce.rol(nombre) VALUES ('Cajero');
INSERT INTO ryce.rol(nombre) VALUES ('Bodeguero');
INSERT INTO ryce.rol(nombre) VALUES ('Inventarista');
INSERT INTO ryce.rol(nombre) VALUES ('Administrador');

/* INSERT SUCURSAL*/
INSERT INTO ryce.sucursal(nombre) VALUES ('Sucursal Central');
INSERT INTO ryce.sucursal(nombre) VALUES ('Sucursal Norte');
INSERT INTO ryce.sucursal(nombre) VALUES ('Sucursal Sur');

/* INSERT DE UN EMPLEADO DE CADA ROL*/
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Erick', 'Morales', 'admin', 'admin', 0, 1, 4);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Daniel', 'Xicará', 'dani96', 'dani123', 2, 1, 1);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Luis', 'García', 'luis96', 'luis123', 0, 1, 2);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Juan', 'Pérez', 'juan96', 'juan123', 0, 1, 3);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Carlos', 'García', 'carlos96', 'carlos123', 0, 2, 1);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Pedro', 'Pérez', 'pedro96', 'pedro123', 0, 2, 2);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Mario', 'García', 'mario96', 'mario123', 0, 2, 3);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('José', 'Pérez', 'jose96', 'jose123', 0, 3, 1);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Jorge', 'García', 'jorge96', 'jorge123', 0, 3, 2);
INSERT INTO ryce.empleado(nombre, apellido, username, password, no_caja, codigo_sucursal, codigo_rol) VALUES ('Javier', 'Pérez', 'javier96', 'javier123', 0, 3, 3);

/*INSERT PRODUCTOS ADMIN SIN REPETIR EL NOMBRE DE PRODUCTO*/

INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Coca Cola', 5.00, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Pepsi', 5.00, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Fanta', 5.00, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Sprite', 5.00, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('7up', 6.25, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Coca Cola Zero', 4.50, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Pepsi Zero', 4.75, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('ChocoKrispis', 13.50, 'Cereal de 150 gramos', 'DelDia');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('ChocoKrispis Jumbo', 37.25, 'Cereal de 900 gramos', 'DelDia');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Coca Cola 3L', 15.00, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Pepsi 3L', 12.20, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Fanta 3L', 12.20, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Sprite 3L', 12.20, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('7up 3L', 12.20, 'Bebida gaseosa', 'Pepsi');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Coca Cola Zero 3L', 12.20, 'Bebida gaseosa', 'Coca Cola');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Verde', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Rojo', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Azul', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Naranja', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Morado', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Doritos Amarillo', 2.99, 'Snack de maíz', 'Frito-Lay');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Agua Mineral', 1.50, 'Agua natural', 'Nestlé');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Pan Integral', 3.25, 'Pan de trigo integral', 'Bimbo');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Leche', 2.25, 'Leche entera', 'Leche Pura');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Hamburguesa', 6.99, 'Hamburguesa de carne', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Papel Higiénico', 1.99, 'Rollo de papel', 'Scott');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Pasta', 2.49, 'Pasta de trigo', 'Barilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Manos', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Manos S', 2.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Manos M', 10.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Manos L', 12.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Manos XL', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Cuerpo', 2.750, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Cuerpo S', 2.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Cuerpo M', 10.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Cuerpo L', 12.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Cuerpo XL', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Capilar', 3.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Capilar S', 2.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Capilar M', 10.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Capilar L', 12.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Capilar XL', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Ropa', 3.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Ropa S', 2.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Ropa M', 10.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Ropa L', 12.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Ropa XL', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Trastes', 3.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Trastes S', 2.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Trastes M', 10.50, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Trastes L', 12.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Jabón de Trastes XL', 14.20, 'Jabón líquido', 'Dove');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal', 3.50, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal S', 2.50, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal M', 10.50, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal L', 12.20, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal XL', 14.20, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal Jumbo', 37.25, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal Jumbo S', 2.50, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal Jumbo M', 10.50, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal Jumbo L', 12.20, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Cereal Jumbo XL', 14.20, 'Cereal de trigo', 'Kellogs');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Gelatina Pelo', 2.50, 'Gelatina para cabello', 'Modo de Gorilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Gelatina Pelo S', 2.50, 'Gelatina para cabello', 'Modo de Gorilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Gelatina Pelo M', 10.50, 'Gelatina para cabello', 'Modo de Gorilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Gelatina Pelo L', 12.20, 'Gelatina para cabello', 'Modo de Gorilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Gelatina Pelo XL', 14.20, 'Gelatina para cabello', 'Modo de Gorilla');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Campero', 2.75, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Campero S', 2.50, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Campero M', 10.50, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Campero L', 12.20, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Campero XL', 14.20, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Campero', 2.75, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Campero S', 2.50, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Campero M', 10.50, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Campero L', 12.20, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Campero XL', 14.20, 'Salsa de tomate', 'Campero');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce McDonalds', 2.75, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce McDonalds S', 2.50, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce McDonalds M', 10.50, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce McDonalds L', 12.20, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce McDonalds XL', 14.20, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante McDonalds', 2.75, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante McDonalds S', 2.50, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante McDonalds M', 10.50, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante McDonalds L', 12.20, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante McDonalds XL', 14.20, 'Salsa de tomate', 'McDonalds');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Burger King', 2.75, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Burger King S', 2.50, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Burger King M', 10.50, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Burger King L', 12.20, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce Burger King XL', 14.20, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Burger King', 2.75, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Burger King S', 2.50, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Burger King M', 10.50, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Burger King L', 12.20, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Picante Burger King XL', 14.20, 'Salsa de tomate', 'Burger King');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce KFC', 2.75, 'Salsa de tomate', 'KFC');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce KFC S', 2.50, 'Salsa de tomate', 'KFC');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce KFC M', 10.50, 'Salsa de tomate', 'KFC');
INSERT INTO rycp.producto(nombre, precio, descripcion, marca) VALUES ('Salsa Dulce KFC L', 12.20, 'Salsa de tomate', 'KFC');

/*INSERT DE LAS CATEGORIAS DE LA TARJETA*/
INSERT INTO rycc.categoriatarjeta(nombre) VALUES ('Común');
INSERT INTO rycc.categoriatarjeta(nombre) VALUES ('Oro');
INSERT INTO rycc.categoriatarjeta(nombre) VALUES ('Platino');
INSERT INTO rycc.categoriatarjeta(nombre) VALUES ('Diamante');

/*INSERT DE C/F*/
INSERT INTO rycc.cliente(nit_cliente, nombre, direccion, no_puntos) VALUES ('CF', 'Consumidor Final', 'Guatemala', 0);
/*INSERT CLIENTES PARA VENTAS*/
INSERT INTO rycc.cliente VALUES ('1667958k', 'Roberto Morales', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207170', 'Mario Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207171', 'Juan Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207172', 'Pedro Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207173', 'Luis Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207174', 'Carlos Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207175', 'Jorge Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207176', 'Javier Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207177', 'Jose Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207178', 'Daniel Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207179', 'Erick Perez', 'Cuidad',0);
INSERT INTO rycc.cliente VALUES ('18207180', 'Roberto Perez', 'Cuidad',0);

/*INSERT TARJETAS*/
INSERT INTO rycc.tarjetapuntos VALUES ('1667958k', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207170', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207171', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207172', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207173', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207174', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207175', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207176', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207177', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207178', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207179', 1, 0);
INSERT INTO rycc.tarjetapuntos VALUES ('18207180', 1, 0);

/*INSERT DE 100 PRODUCTOS DE SUCURSAL 1 (CENTRAL) */
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 1, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 2, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 3, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 4, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 5, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 6, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 7, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 8, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 9, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 10, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 11, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 12, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 13, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 14, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 15, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 16, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 17, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 18, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 19, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 20, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 21, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 22, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 23, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 24, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 25, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 26, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 27, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 28, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 29, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 30, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 31, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 32, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 33, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 34, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 35, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 36, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 37, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 38, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 39, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 40, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 41, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 42, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 43, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 44, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 45, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 46, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 47, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 48, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 49, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 50, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 51, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 52, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 53, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 54, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 55, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 56, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 57, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 58, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 59, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 60, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 61, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 62, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 63, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 64, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 65, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 66, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 67, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 68, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 69, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 70, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 71, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 72, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 73, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 74, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 75, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 76, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 77, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 78, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 79, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 80, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 81, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 82, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 83, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 84, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 85, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 86, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 87, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 88, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 89, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 90, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 91, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 92, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 93, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 94, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 95, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 96, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 97, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 98, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 99, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (1, 100, 100);

/*INSERTE DE LOS PRODUCTOS A ESTANTERIA SUCURSAL 1*/
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 1, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 2, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 3, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 4, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 5, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 6, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 7, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 8, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 9, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 10, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 11, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 12, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 13, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 14, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 15, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 16, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 17, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 18, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 19, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 20, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 21, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 22, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 23, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 24, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 25, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 26, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 27, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 28, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 29, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 30, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 31, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 32, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 33, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 34, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 35, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 36, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 37, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 38, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 39, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 40, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 41, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 42, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 43, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 44, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 45, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 46, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 47, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 48, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 49, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 50, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 51, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 52, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 53, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 54, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 55, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 56, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 57, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 58, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 59, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 60, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 61, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 62, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 63, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 64, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 65, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 66, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 67, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 68, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 69, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 70, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 71, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 72, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 73, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 74, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 75, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 76, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 77, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 78, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 79, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 80, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 81, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 82, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 83, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 84, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 85, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 86, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 87, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 88, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 89, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 90, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 91, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 92, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 93, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 94, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 95, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 96, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 97, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 98, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 99, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (1, 100,100,10);

/*INSERT 75 PRODUCTOS EN SUCURSAL 2 */
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 25, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 26, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 27, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 28, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 29, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 30, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 31, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 32, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 33, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 34, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 35, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 36, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 37, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 38, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 39, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 40, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 41, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 42, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 43, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 44, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 45, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 46, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 47, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 48, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 49, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 50, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 51, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 52, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 53, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 54, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 55, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 56, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 57, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 58, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 59, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 60, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 61, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 62, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 63, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 64, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 65, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 66, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 67, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 68, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 69, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 70, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 71, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 72, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 73, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 74, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 75, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 76, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 77, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 78, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 79, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 80, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 81, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 82, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 83, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 84, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 85, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 86, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 87, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 88, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 89, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 90, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 91, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 92, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 93, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 94, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 95, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 96, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 97, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 98, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 99, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (2, 100, 100);
/*INSERT A SUCURSAL 2, ESTANTERIA*/
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 25, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 26, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 27, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 28, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 29, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 30, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 31, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 32, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 33, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 34, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 35, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 36, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 37, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 38, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 39, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 40, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 41, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 42, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 43, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 44, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 45, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 46, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 47, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 48, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 49, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 50, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 51, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 52, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 53, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 54, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 55, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 56, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 57, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 58, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 59, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 60, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 61, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 62, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 63, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 64, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 65, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 66, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 67, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 68, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 69, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 70, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 71, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 72, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 73, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 74, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 75, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 76, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 77, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 78, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 79, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 80, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 81, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 82, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 83, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 84, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 85, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 86, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 87, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 88, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 89, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 90, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 91, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 92, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 93, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 94, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 95, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 96, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 97, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 98, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 99, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (2, 100, 100,11);

/*INSERT 75 PRODUCTOS EN SUCURSAL 3 */
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 1, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 2, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 3, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 4, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 5, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 6, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 7, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 8, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 9, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 10, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 11, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 12, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 13, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 14, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 15, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 16, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 17, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 18, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 19, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 20, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 21, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 22, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 23, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 24, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 25, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 26, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 27, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 28, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 29, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 30, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 31, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 32, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 33, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 34, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 35, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 36, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 37, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 38, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 39, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 40, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 41, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 42, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 43, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 44, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 45, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 46, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 47, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 48, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 49, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 50, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 51, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 52, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 53, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 54, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 55, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 56, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 57, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 58, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 59, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 60, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 61, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 62, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 63, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 64, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 65, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 66, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 67, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 68, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 69, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 70, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 71, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 72, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 73, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 74, 100);
INSERT INTO rycp.bodega(sucursal, producto, cantidad) VALUES (3, 75, 100);

/*INSERT ESTANTERIA SUCURSAL 3*/
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 1, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 2, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 3, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 4, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 5, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 6, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 7, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 8, 100,1);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 9, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 10, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 11, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 12, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 13, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 14, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 15, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 16, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 17, 100,2);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 18, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 19, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 20, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 21, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 22, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 23, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 24, 100,3);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 25, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 26, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 27, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 28, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 29, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 30, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 31, 100,4);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 32, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 33, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 34, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 35, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 36, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 37, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 38, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 39, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 40, 100,5);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 41, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 42, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 43, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 44, 100,6);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 45, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 46, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 47, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 48, 100,7);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 49, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 50, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 51, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 52, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 53, 100,8);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 54, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 55, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 56, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 57, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 58, 100,9);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 59, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 60, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 61, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 62, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 63, 100,10);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 64, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 65, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 66, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 67, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 68, 100,11);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 69, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 70, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 71, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 72, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 73, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 74, 100,12);
INSERT INTO rycp.estanteria(sucursal, producto, cantidad, no_pasillo) VALUES (3, 75, 100,12);