/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.danimo.chapin.market.view;

import com.danimo.chapin.market.daoImpl.EmpleadoDaoImpl;
import com.danimo.chapin.market.daoImpl.ProductoDaoImpl;
import com.danimo.chapin.market.model.Empleado;
import com.danimo.chapin.market.model.Producto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.beans.PropertyVetoException;
import java.util.ArrayList;

/**
 *
 * @author danimo
 */
public class AdminView extends javax.swing.JInternalFrame {
    private Empleado empleado;
    private int id_empleado;

    /**
     * Creates new form AdminView
     */
    public AdminView(int id) throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        this.setResizable(true);
        this.id_empleado= id;
        empleado= new EmpleadoDaoImpl().obtenerPorId(this.id_empleado);
        this.name_admin_txt.setText(empleado.getNombre()+" "+ empleado.getApellido());
        this.mostrarEmpleados();
        this.mostrarProductos();

    }

    public void mostrarEmpleados(){
        ArrayList<Empleado> list_empleados= new ArrayList();
        list_empleados= new EmpleadoDaoImpl().obtenerTodos();
        //Creare una tabla para mostrar los datos, y mostrarlos en mi JFrame de AdminView
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("No. Caja");
        modelo.addColumn("Sucursal");
        modelo.addColumn("Rol");
        if(list_empleados.size()>0){
            for (Empleado empleado: list_empleados){
                if(empleado.getNo_caja()==0){
                    modelo.addRow(new Object[]{
                            empleado.getId(),
                            empleado.getNombre(),
                            empleado.getApellido(),
                            " ",
                            empleado.getSucursal_id(),
                            empleado.getRol_id()
                    });
                }else{
                    modelo.addRow(new Object[]{
                            empleado.getId(),
                            empleado.getNombre(),
                            empleado.getApellido(),
                            empleado.getNo_caja(),
                            empleado.getSucursal_id(),
                            empleado.getRol_id()
                    });
                }
            }
        }
        this.jTable1.setModel(modelo);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    public void mostrarProductos(){
        //Aqui mostrare los productos existentes, en la Jtable 2
        ArrayList<Producto> list_productos= new ArrayList();
        list_productos= new ProductoDaoImpl().obtenerTodos();
        //Creare una tabla para mostrar los datos, y mostrarlos en mi JFrame de AdminView
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Marca");
        if(list_productos.size()>0){
            for (Producto producto: list_productos){
                modelo.addRow(new Object[]{
                        producto.getCodigo_producto(),
                        producto.getNombre(),
                        producto.getDescripcion(),
                        producto.getPrecio(),
                        producto.getMarca()
                });
            }
        }
        this.jTable2.setModel(modelo);
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_admin_txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 33, -1, -1));

        name_admin_txt.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(name_admin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 33, 320, 29));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 144, 960, 280));

        jLabel2.setText("LISTA DE EMPLEADOS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 103, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Actualizar Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 220, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 960, 370));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("LISTA DE PRODUCTOS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Actualizar Productos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 230, 40));

        jMenu1.setText("Registro");

        jMenuItem1.setText("Añadir Empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Añadir Producto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        jMenuItem5.setText("Historial Descuentos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem2.setText("Reporte top 10 Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Ingresos Sucursales");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Articulos Mas Vendidos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Mejores Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cerrar");

        jMenuItem3.setText("Cerrar Sesion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO aqui va el codigo para abrir el formulario de registro de empleados
        try {
            System.out.println("Voy a abrir el formulario de registro de empleados");
            Registrar_Usuario registroEmpleados= new Registrar_Usuario();
            Main.MainP.add(registroEmpleados);
            System.out.println("Agregue el formulario de registro de empleados");
            registroEmpleados.show();
            System.out.println("Mostre el formulario de registro de empleados");
            this.toBack();
            registroEmpleados.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO actualizare la tabla de empelados:
        this.mostrarEmpleados();
        JOptionPane.showMessageDialog(null, "Se actualizaron los empleados");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Main.MainP.removeAll();
        Main.MainP.repaint();
        Login login = null;
        try {
            login = new Login();
            login.setVisible(true);
            Main.MainP.add(login);
            Main.MainP.moveToFront(login);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO aqui va el codigo para abrir el formulario de registro de empleados
        try {
            System.out.println("Voy a abrir el formulario de registro de empleados");
            NewProductView registroProducto= new NewProductView();
            Main.MainP.add(registroProducto);
            System.out.println("Agregue el formulario de registro de empleados");
            registroProducto.show();
            System.out.println("Mostre el formulario de registro de empleados");
            this.toBack();
            registroProducto.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.mostrarProductos();
        JOptionPane.showMessageDialog(null, "Se actualizaron los productos");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try {
            Reporte1 reporte1= new Reporte1();
            Main.MainP.add(reporte1);
            reporte1.show();
            this.toBack();
            reporte1.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         try {
            Reporte2 reporte2= new Reporte2();
            Main.MainP.add(reporte2);
            reporte2.show();
            this.toBack();
            reporte2.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            Reporte3 reporte3= new Reporte3();
            Main.MainP.add(reporte3);
            reporte3.show();
            this.toBack();
            reporte3.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            Reporte4 reporte4= new Reporte4();
            Main.MainP.add(reporte4);
            reporte4.show();
            this.toBack();
            reporte4.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
          try {
            Reporte5 reporte5= new Reporte5();
            Main.MainP.add(reporte5);
            reporte5.show();
            this.toBack();
            reporte5.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el formulario de registro de empleados");
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JLabel name_admin_txt;
    // End of variables declaration//GEN-END:variables
}
