/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.danimo.chapin.market.view;

import com.danimo.chapin.market.model.Empleado;
import com.danimo.chapin.market.enums.Rol;
import com.danimo.chapin.market.handlers.MLogin;
import static com.danimo.chapin.market.view.AdminView.name_admin_txt;
import static com.danimo.chapin.market.view.BodegaView.name_txt_bodega;
import static com.danimo.chapin.market.view.CajeroView.name_vendedor_txt;
import static com.danimo.chapin.market.view.InventaristaView.name_inventarista_txt;

import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;

/**
 *
 * @author danimo
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    private Image image;
    public Login() throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setResizable(true);
        setTitle("LOGIN");
        setToolTipText("");

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/danimo/NetBeansProjects/Chapin-Market/Chapin-Market/imgs/img1.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 481, 210));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Username: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 341, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Password: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 341, -1));

        username_txt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 255, -1));

        password_txt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 255, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
         * Metodo para realizar la consulta a la bd, obtiene los datos de
         * los txt y almacena en variables
         */
        try {
            String username="@"; 
            String password="@";
            username= username_txt.getText();
            password= password_txt.getText();
            if(username.equals("@") || password.equals("@")){
                JOptionPane.showMessageDialog(null, "Campos nulos, verifique");
            }else{
                MLogin consult_login= new MLogin();
                int result=consult_login.validarUsuario(username, password);
                if(username.equals("") || password.equals("")){
                    JOptionPane.showMessageDialog(null, "Campos nulos, verifique");
                }else if(result==-1){
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos, Vuelva a intentarlo");
                    username_txt.setText("");
                    password_txt.setText("");
                }else{
                    // AQUI VA PARA VER A QUE VENTANA DEBE IRSE (EL NUEVO ROLL)
                    Empleado emp= consult_login.obtenerEmpleado(result);
                    JOptionPane.showMessageDialog(null,"Bienvenido "+ emp.getNombre());
                    username_txt.setText("");
                    password_txt.setText("");
                    if(emp.getRol_id().equals(Rol.ADMINISTRADOR)){
                        Main.MainP.removeAll();
                        AdminView admin_view = new AdminView(emp.getId());
                        Main.MainP.add(admin_view);
                        admin_view.show();
                        name_admin_txt.setText(emp.getNombre()+" "+ emp.getApellido());
                    }else if(emp.getRol_id().equals(Rol.BODEGUERO)){
                        Main.MainP.removeAll();
                        BodegaView cajero_view = new BodegaView(emp.getId());
                        Main.MainP.add(cajero_view);
                        cajero_view.show();
                        name_txt_bodega.setText(emp.getNombre()+" "+ emp.getApellido());
                    }else if(emp.getRol_id().equals(Rol.INVENTARISTA)) {
                        Main.MainP.removeAll();
                        CajeroView cajero_view = new CajeroView(emp.getId());
                        Main.MainP.add(cajero_view);
                        cajero_view.show();
                        name_vendedor_txt.setText(emp.getNombre() + " " + emp.getApellido());
                    } else if ( emp.getRol_id().equals(Rol.CAJERO)) {
                        Main.MainP.removeAll();
                        InventaristaView cajero_view = new InventaristaView(emp.getId());
                        Main.MainP.add(cajero_view);
                        cajero_view.show();
                        name_inventarista_txt.setText(emp.getNombre() + " " + emp.getApellido());
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al iniciar sesion");
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password_txt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
