/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.danimo.chapin.market.view;

import com.danimo.chapin.market.daoImpl.EmpleadoDaoImpl;
import com.danimo.chapin.market.enums.Rol;
import com.danimo.chapin.market.enums.Sucursal;
import com.danimo.chapin.market.model.Empleado;

import java.beans.PropertyVetoException;

/**
 *
 * @author danimo
 */
public class Registrar_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Usuario
     */
    public Registrar_Usuario() throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        last_name_txt = new javax.swing.JTextField();
        username_txt = new javax.swing.JTextField();
        no_caja_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        combo_sucursal = new javax.swing.JComboBox<>();
        combo_tipo_usuario = new javax.swing.JComboBox<>();
        button_save = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Registrar Nuevo Empleado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 115, 350, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 278, 633, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 165, 350, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 227, 350, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("No Caja");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 633, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Sucursal:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 633, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Tipo Usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 130, -1));
        getContentPane().add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 470, 34));
        getContentPane().add(last_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 470, 34));
        getContentPane().add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 470, 34));
        getContentPane().add(no_caja_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 470, 34));
        getContentPane().add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 470, 34));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 470, 34));

        combo_sucursal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        combo_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central", "Norte", "Sur" }));
        getContentPane().add(combo_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 470, -1));

        combo_tipo_usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        combo_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Bodeguero", "Inventarista", "Administrador" }));
        combo_tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipo_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(combo_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 470, -1));

        button_save.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button_save.setText("Guardar Usuario");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });
        getContentPane().add(button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipo_usuarioActionPerformed
        // TODO add your handling code here:
        if(combo_tipo_usuario.getSelectedItem().toString().equals("Administrador")){
            no_caja_txt.setEnabled(false);
            combo_sucursal.setEnabled(false);
        }else if(combo_tipo_usuario.getSelectedItem().toString().equals("Cajero")) {
            no_caja_txt.setEnabled(true);
            combo_sucursal.setEnabled(true);
        }else if(combo_tipo_usuario.getSelectedItem().toString().equals("Bodeguero")) {
            no_caja_txt.setEnabled(false);
            combo_sucursal.setEnabled(true);
        }else if(combo_tipo_usuario.getSelectedItem().toString().equals("Inventarista")) {
            no_caja_txt.setEnabled(false);
            combo_sucursal.setEnabled(true);
        }
    }//GEN-LAST:event_combo_tipo_usuarioActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO Guardare un nuevo empleado
        String nombre = name_txt.getText();
        String apellido = last_name_txt.getText();
        String username = username_txt.getText();
        String password = password_txt.getText();
        if(no_caja_txt.getText().equals("")){
            no_caja_txt.setText("0");
        }
        int no_caja = Integer.parseInt(no_caja_txt.getText());
        int sucursal = combo_sucursal.getSelectedIndex()+1;
        if(combo_tipo_usuario.getSelectedItem().toString().equals("Administrador")){
            no_caja = 0;
            sucursal = 1;
        }
        int tipo_usuario = combo_tipo_usuario.getSelectedIndex()+1;
        Empleado empleado = new Empleado(nombre, apellido, username, password, no_caja, Sucursal.getSucursal(sucursal), Rol.getRol(tipo_usuario));
        new EmpleadoDaoImpl().insertar(empleado);
        System.out.println(empleado.toString());
        this.clearAll();


    }//GEN-LAST:event_button_saveActionPerformed

    public void clearAll(){
        name_txt.setText("");
        last_name_txt.setText("");
        username_txt.setText("");
        password_txt.setText("");
        no_caja_txt.setText("");
        combo_sucursal.setSelectedIndex(0);
        combo_tipo_usuario.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_save;
    private javax.swing.JComboBox<String> combo_sucursal;
    private javax.swing.JComboBox<String> combo_tipo_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField last_name_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField no_caja_txt;
    private javax.swing.JTextField password_txt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
