/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.danimo.chapin.market.view;

import com.danimo.chapin.market.daoImpl.ClienteDaoImpl;
import com.danimo.chapin.market.daoImpl.EmpleadoDaoImpl;
import com.danimo.chapin.market.daoImpl.ReportesDaoImpl;
import com.danimo.chapin.market.model.ReporteDescuento;
import com.danimo.chapin.market.model.Venta;

import javax.swing.table.DefaultTableModel;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import static com.danimo.chapin.market.enums.Sucursal.getStringSucursal;

/**
 *
 * @author danimo
 */
public class Reporte2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reporte1
     */
    public Reporte2() throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        this.setResizable(true);
        this.agregarFomatoTable();
    }
    
    public void agregarFomatoTable(){
    
        //TODO: agregar los nombres de las columnas de mi tabla
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Correlativo");
        model.addColumn("No. Factura");
        model.addColumn("Fecha");
        model.addColumn("Subtotal");
        model.addColumn("Descuento");
        model.addColumn("Total");
        model.addColumn("Nombre Cliente");
        model.addColumn("Nombre Empleado");
        model.addColumn("Sucursal");
        this.table_resultados.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resultados = new javax.swing.JTable();
        fecha_inicial = new javax.swing.JFormattedTextField();
        fecha_final = new javax.swing.JFormattedTextField();
        boton_buscar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Mayores Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Fecha Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Fecha Final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        table_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_resultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 1440, 660));

        try {
            fecha_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha_inicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha_inicial.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(fecha_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 290, -1));

        try {
            fecha_final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha_final.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha_final.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 290, -1));

        boton_buscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        // TODO: obtener fechas de los txt y hacer las busquedas a la bd:
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaInicial = this.fecha_inicial.getText();
        String fechaFinal = this.fecha_final.getText();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fecha = LocalDate.parse(fechaInicial, formatter);
        LocalDate fecha1 = LocalDate.parse(fechaFinal, formatter);

        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fecha_inicial_formateada = fecha.format(formatter1);
        String fecha_final_formateada = fecha1.format(formatter1);


        ArrayList<Venta> reporteDescuentos = new ReportesDaoImpl().top10Ventas(fecha_inicial_formateada, fecha_final_formateada);
        //TODO: agrego los campos a la tabla
        int contador=1;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Correlativo");
        model.addColumn("No. Factura");
        model.addColumn("Fecha");
        model.addColumn("Subtotal");
        model.addColumn("Descuento");
        model.addColumn("Total");
        model.addColumn("Nombre Cliente");
        model.addColumn("Nombre Empleado");
        model.addColumn("Sucursal");
       for (Venta venta: reporteDescuentos){
           model.addRow(new Object[]{
                   contador++,
                   venta.getCodigo_venta(),
                   venta.getFecha().format(formatter),
                   venta.getSubtotal(),
                   venta.getDescuento(),
                   venta.getTotal(),
                   new ClienteDaoImpl().obtenerPorNit(venta.getNit_cliente()).getNombre(),
                   new EmpleadoDaoImpl().obtenerPorId(venta.getCodigo_empleado()).getNombre(),
                   getStringSucursal(new EmpleadoDaoImpl().obtenerPorId(venta.getCodigo_empleado()).getSucursal_id()),
           });
       }
        this.table_resultados.setModel(model);




    }//GEN-LAST:event_boton_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JFormattedTextField fecha_final;
    private javax.swing.JFormattedTextField fecha_inicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_resultados;
    // End of variables declaration//GEN-END:variables
}
