/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.danimo.chapin.market.view;

import com.danimo.chapin.market.daoImpl.ClienteDaoImpl;
import com.danimo.chapin.market.daoImpl.EmpleadoDaoImpl;
import com.danimo.chapin.market.daoImpl.ReportesDaoImpl;
import com.danimo.chapin.market.model.ReporteArticulosMasVendidos;
import com.danimo.chapin.market.model.ReporteClientesDinero;
import com.danimo.chapin.market.model.ReporteDescuento;
import com.danimo.chapin.market.model.Venta;

import javax.swing.table.DefaultTableModel;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import static com.danimo.chapin.market.enums.Sucursal.getStringSucursal;

/**
 *
 * @author danimo
 */
public class Reporte5 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reporte1
     */
    public Reporte5() throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
        this.setResizable(true);
        this.agregarFomatoTable();
        this.obtenerClientesMasCompras();
    }
    
    public void agregarFomatoTable(){
    
        //TODO: agregar los nombres de las columnas de mi tabla
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nit Cliente");
        model.addColumn("Nombre Cliente");
        model.addColumn("Direccion");
        model.addColumn("Puntos");
        model.addColumn("Total Gastado");
        this.table_resultados.setModel(model);
    }

    public void obtenerClientesMasCompras(){
        ArrayList<ReporteClientesDinero> reporteClientesDinero = new ReportesDaoImpl().top10Clientes();
        DefaultTableModel model = (DefaultTableModel) this.table_resultados.getModel();
        for (ReporteClientesDinero reporteClienteDinero : reporteClientesDinero) {
            model.addRow(new Object[]{
                    reporteClienteDinero.getCliente().getNit(),
                    reporteClienteDinero.getCliente().getNombre(),
                    reporteClienteDinero.getCliente().getDireccion(),
                    reporteClienteDinero.getCliente().getNo_puntos(),
                    reporteClienteDinero.getDineroGastado()
            });
        }
        this.table_resultados.setModel(model);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resultados = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Articulos Mas Vendidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 32, -1, -1));

        table_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_resultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 1440, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_resultados;
    // End of variables declaration//GEN-END:variables
}
